name: taskify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  hooks_riverpod: ^2.4.5
  google_fonts: ^5.1.0
  flutter_vector_icons: ^2.0.0
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.21
  pinput: ^3.0.1
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  sqflite: ^2.3.0
  dynamic_color: ^1.6.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
